/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// package.json
var require_package = __commonJS({
  "package.json"(exports, module2) {
    module2.exports = {
      name: "obsidian-paste-image-rename",
      version: "1.6.1",
      main: "main.js",
      scripts: {
        start: "node esbuild.config.mjs",
        build: "tsc -noEmit -skipLibCheck && BUILD_ENV=production node esbuild.config.mjs && cp manifest.json build",
        version: "node version-bump.mjs && git add manifest.json versions.json",
        release: "npm run build && gh release create ${npm_package_version} build/*"
      },
      keywords: [],
      author: "Reorx",
      license: "MIT",
      devDependencies: {
        "@types/node": "^24.10.4",
        "@typescript-eslint/eslint-plugin": "^5.49.0",
        "@typescript-eslint/parser": "^5.49.0",
        "builtin-modules": "^3.3.0",
        esbuild: "^0.27.2",
        obsidian: "^1.11.0",
        tslib: "2.5.0",
        typescript: "^5.9.3"
      },
      dependencies: {
        "cash-dom": "^8.1.2"
      }
    };
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PasteImageRenamePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/batch.ts
var import_obsidian2 = require("obsidian");

// src/utils.ts
var DEBUG = false;
if (DEBUG) console.log("DEBUG is enabled");
function debugLog(...args) {
  if (DEBUG) {
    console.log((/* @__PURE__ */ new Date()).toISOString().slice(11, 23), ...args);
  }
}
function createElementTree(rootEl, opts) {
  const result = {
    el: rootEl.createEl(opts.tag, opts),
    children: []
  };
  const children = opts.children || [];
  for (const child of children) {
    result.children.push(createElementTree(result.el, child));
  }
  return result;
}
var path = {
  // Credit: @creationix/path.js
  join(...partSegments) {
    let parts = [];
    for (let i = 0, l = partSegments.length; i < l; i++) {
      parts = parts.concat(partSegments[i].split("/"));
    }
    const newParts = [];
    for (let i = 0, l = parts.length; i < l; i++) {
      const part = parts[i];
      if (!part || part === ".") continue;
      else newParts.push(part);
    }
    if (parts[0] === "") newParts.unshift("");
    return newParts.join("/");
  },
  // returns the last part of a path, e.g. 'foo.jpg'
  basename(fullpath) {
    const sp = fullpath.split("/");
    return sp[sp.length - 1];
  },
  // return extension without dot, e.g. 'jpg'
  extension(fullpath) {
    const positions = [...fullpath.matchAll(new RegExp("\\.", "gi"))].map((a) => a.index);
    return fullpath.slice(positions[positions.length - 1] + 1);
  }
};
var filenameNotAllowedChars = /[^\p{L}0-9~`!@$&*()\-_=+{};'",<.>? ]/ug;
var sanitizer = {
  filename(s) {
    return s.replace(filenameNotAllowedChars, "").trim();
  },
  delimiter(s) {
    s = this.filename(s);
    if (!s) s = "-";
    return s;
  }
};
function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function lockInputMethodComposition(el) {
  const state = {
    lock: false
  };
  el.addEventListener("compositionstart", () => {
    state.lock = true;
  });
  el.addEventListener("compositionend", () => {
    state.lock = false;
  });
  return state;
}

// src/i18n.ts
var import_obsidian = require("obsidian");
var translations = {
  en: {
    // Common
    "common.cancel": "Cancel",
    "common.yes": "Yes",
    "common.no": "No",
    "common.to": "to",
    // Errors & Notices
    "error.noActiveFile": "Error: No active file found.",
    "error.renameFailed": "Failed to rename",
    "error.noActiveEditor": "no active editor",
    "notice.renamed": "Renamed",
    "error.batchRenameFailed": "Failed to batch rename images: the generated name is not meaningful",
    // Image Rename Modal
    "modal.rename.title": "Rename image",
    "modal.rename.newName": "New name",
    "modal.rename.newNameDesc": "Please input the new name for the image (without extension)",
    "modal.rename.originPath": "Origin path",
    "modal.rename.newPath": "New path",
    "modal.rename.button": "Rename",
    "modal.rename.errorEmpty": 'Error: "New name" could not be empty',
    // Batch Rename Modal
    "modal.batch.title": "Batch rename embeded files",
    "modal.batch.namePattern": "Name pattern",
    "modal.batch.namePatternDesc": "Please input the name pattern to match files (regex)",
    "modal.batch.extPattern": "Extension pattern",
    "modal.batch.extPatternDesc": "Please input the extension pattern to match files (regex)",
    "modal.batch.nameReplace": "Name replace",
    "modal.batch.nameReplaceDesc": "Please input the string to replace the matched name (use $1, $2 for regex groups)",
    "modal.batch.tableOriginal": "Original path",
    "modal.batch.tableRenamed": "Renamed Name",
    "modal.batch.renameAll": "Rename all",
    "modal.batch.errorEmpty": 'Error: "Name pattern" could not be empty',
    "modal.batch.confirmTitle": "Confirm rename all",
    "modal.batch.confirmMessage": "Are you sure? This will rename all the {count} images matched the pattern.",
    // Commands
    "command.batchRename": "Batch rename embeded files (in the current file)",
    "command.batchRenameAll": "Batch rename all images instantly (in the current file)",
    // Settings
    "setting.imageNamePattern.name": "Image name pattern",
    "setting.imageNamePattern.desc": `The pattern indicates how the new name should be generated.

Available variables:
- {{fileName}}: name of the active file, without ".md" extension.
- {{dirName}}: name of the directory which contains the document (the root directory of vault results in an empty variable).
- {{imageNameKey}}: this variable is read from the markdown file's frontmatter, from the same key "imageNameKey".
- {{DATE:$FORMAT}}: use "$FORMAT" to format the current date, "$FORMAT" must be a Moment.js format string, e.g. {{DATE:YYYY-MM-DD}}.

Here are some examples from pattern to image names (repeat in sequence), variables: fileName = "My note", imageNameKey = "foo":
- {{fileName}}: My note, My note-1, My note-2
- {{imageNameKey}}: foo, foo-1, foo-2
- {{imageNameKey}}-{{DATE:YYYYMMDD}}: foo-20220408, foo-20220408-1, foo-20220408-2`,
    "setting.dupNumberAtStart.name": "Duplicate number at start (or end)",
    "setting.dupNumberAtStart.desc": "If enabled, duplicate number will be added at the start as prefix for the image name, otherwise it will be added at the end as suffix for the image name.",
    "setting.dupNumberDelimiter.name": "Duplicate number delimiter",
    "setting.dupNumberDelimiter.desc": 'The delimiter to generate the number prefix/suffix for duplicated names. For example, if the value is "-", the suffix will be like "-1", "-2", "-3", and the prefix will be like "1-", "2-", "3-". Only characters that are valid in file names are allowed.',
    "setting.dupNumberAlways.name": "Always add duplicate number",
    "setting.dupNumberAlways.desc": "If enabled, duplicate number will always be added to the image name. Otherwise, it will only be added when the name is duplicated.",
    "setting.autoRename.name": "Auto rename",
    "setting.autoRename.desc": "By default, the rename modal will always be shown to confirm before renaming, if this option is set, the image will be auto renamed after pasting.",
    "setting.handleAllAttachments.name": "Handle all attachments",
    "setting.handleAllAttachments.desc": `By default, the plugin only handles images that starts with "Pasted image " in name,
which is the prefix Obsidian uses to create images from pasted content.
If this option is set, the plugin will handle all attachments that are created in the vault.`,
    "setting.excludeExtensionPattern.name": "Exclude extension pattern",
    "setting.excludeExtensionPattern.desc": `This option is only useful when "Handle all attachments" is enabled.
Write a Regex pattern to exclude certain extensions from being handled. Only the first line will be used.`,
    "setting.disableRenameNotice.name": "Disable rename notice",
    "setting.disableRenameNotice.desc": `Turn off this option if you don't want to see the notice when renaming images.
Note that Obsidian may display a notice when a link has changed, this option cannot disable that.`
  },
  zh: {
    // Common
    "common.cancel": "\u53D6\u6D88",
    "common.yes": "\u786E\u5B9A",
    "common.no": "\u53D6\u6D88",
    "common.to": "\u5230",
    // Errors & Notices
    "error.noActiveFile": "\u9519\u8BEF\uFF1A\u672A\u627E\u5230\u6D3B\u52A8\u6587\u4EF6\u3002",
    "error.renameFailed": "\u91CD\u547D\u540D\u5931\u8D25",
    "error.noActiveEditor": "\u6CA1\u6709\u6D3B\u52A8\u7684\u7F16\u8F91\u5668",
    "notice.renamed": "\u5DF2\u91CD\u547D\u540D",
    "error.batchRenameFailed": "\u6279\u91CF\u91CD\u547D\u540D\u56FE\u7247\u5931\u8D25\uFF1A\u751F\u6210\u7684\u540D\u79F0\u65E0\u610F\u4E49",
    // Image Rename Modal
    "modal.rename.title": "\u91CD\u547D\u540D\u56FE\u7247",
    "modal.rename.newName": "\u65B0\u540D\u79F0",
    "modal.rename.newNameDesc": "\u8BF7\u8F93\u5165\u56FE\u7247\u7684\u65B0\u540D\u79F0\uFF08\u4E0D\u542B\u6269\u5C55\u540D\uFF09",
    "modal.rename.originPath": "\u539F\u8DEF\u5F84",
    "modal.rename.newPath": "\u65B0\u8DEF\u5F84",
    "modal.rename.button": "\u91CD\u547D\u540D",
    "modal.rename.errorEmpty": '\u9519\u8BEF\uFF1A"\u65B0\u540D\u79F0"\u4E0D\u80FD\u4E3A\u7A7A',
    // Batch Rename Modal
    "modal.batch.title": "\u6279\u91CF\u91CD\u547D\u540D\u5D4C\u5165\u6587\u4EF6",
    "modal.batch.namePattern": "\u540D\u79F0\u6A21\u5F0F",
    "modal.batch.namePatternDesc": "\u8BF7\u8F93\u5165\u5339\u914D\u6587\u4EF6\u7684\u540D\u79F0\u6A21\u5F0F\uFF08\u6B63\u5219\u8868\u8FBE\u5F0F\uFF09",
    "modal.batch.extPattern": "\u6269\u5C55\u540D\u6A21\u5F0F",
    "modal.batch.extPatternDesc": "\u8BF7\u8F93\u5165\u5339\u914D\u6587\u4EF6\u7684\u6269\u5C55\u540D\u6A21\u5F0F\uFF08\u6B63\u5219\u8868\u8FBE\u5F0F\uFF09",
    "modal.batch.nameReplace": "\u540D\u79F0\u66FF\u6362",
    "modal.batch.nameReplaceDesc": "\u8BF7\u8F93\u5165\u7528\u4E8E\u66FF\u6362\u5339\u914D\u540D\u79F0\u7684\u5B57\u7B26\u4E32\uFF08\u4F7F\u7528 $1\u3001$2 \u8868\u793A\u6B63\u5219\u5206\u7EC4\uFF09",
    "modal.batch.tableOriginal": "\u539F\u8DEF\u5F84",
    "modal.batch.tableRenamed": "\u91CD\u547D\u540D\u540E\u7684\u540D\u79F0",
    "modal.batch.renameAll": "\u5168\u90E8\u91CD\u547D\u540D",
    "modal.batch.errorEmpty": '\u9519\u8BEF\uFF1A"\u540D\u79F0\u6A21\u5F0F"\u4E0D\u80FD\u4E3A\u7A7A',
    "modal.batch.confirmTitle": "\u786E\u8BA4\u5168\u90E8\u91CD\u547D\u540D",
    "modal.batch.confirmMessage": "\u786E\u5B9A\u8981\u7EE7\u7EED\u5417\uFF1F\u8FD9\u5C06\u91CD\u547D\u540D\u6240\u6709\u5339\u914D\u7684 {count} \u4E2A\u56FE\u7247\u3002",
    // Commands
    "command.batchRename": "\u6279\u91CF\u91CD\u547D\u540D\u5D4C\u5165\u6587\u4EF6\uFF08\u5F53\u524D\u6587\u4EF6\uFF09",
    "command.batchRenameAll": "\u7ACB\u5373\u6279\u91CF\u91CD\u547D\u540D\u6240\u6709\u56FE\u7247\uFF08\u5F53\u524D\u6587\u4EF6\uFF09",
    // Settings
    "setting.imageNamePattern.name": "\u56FE\u7247\u540D\u79F0\u6A21\u5F0F",
    "setting.imageNamePattern.desc": `\u6B64\u6A21\u5F0F\u6307\u5B9A\u5982\u4F55\u751F\u6210\u65B0\u540D\u79F0\u3002

\u53EF\u7528\u53D8\u91CF\uFF1A
- {{fileName}}\uFF1A\u6D3B\u52A8\u6587\u4EF6\u7684\u540D\u79F0\uFF0C\u4E0D\u542B ".md" \u6269\u5C55\u540D\u3002
- {{dirName}}\uFF1A\u5305\u542B\u6587\u6863\u7684\u76EE\u5F55\u540D\u79F0\uFF08\u6839\u76EE\u5F55\u7ED3\u679C\u4E3A\u7A7A\u53D8\u91CF\uFF09\u3002
- {{imageNameKey}}\uFF1A\u6B64\u53D8\u91CF\u4ECE markdown \u6587\u4EF6\u7684 frontmatter \u4E2D\u8BFB\u53D6\uFF0C\u952E\u540D\u4E3A "imageNameKey"\u3002
- {{DATE:$FORMAT}}\uFF1A\u4F7F\u7528 "$FORMAT" \u683C\u5F0F\u5316\u5F53\u524D\u65E5\u671F\uFF0C"$FORMAT" \u5FC5\u987B\u662F Moment.js \u683C\u5F0F\u5B57\u7B26\u4E32\uFF0C\u4F8B\u5982 {{DATE:YYYY-MM-DD}}\u3002

\u793A\u4F8B\uFF08\u53D8\u91CF\uFF1AfileName = "\u6211\u7684\u7B14\u8BB0", imageNameKey = "foo"\uFF09\uFF1A
- {{fileName}}\uFF1A\u6211\u7684\u7B14\u8BB0, \u6211\u7684\u7B14\u8BB0-1, \u6211\u7684\u7B14\u8BB0-2
- {{imageNameKey}}\uFF1Afoo, foo-1, foo-2
- {{imageNameKey}}-{{DATE:YYYYMMDD}}\uFF1Afoo-20220408, foo-20220408-1, foo-20220408-2`,
    "setting.dupNumberAtStart.name": "\u91CD\u590D\u7F16\u53F7\u5728\u5F00\u5934\uFF08\u6216\u672B\u5C3E\uFF09",
    "setting.dupNumberAtStart.desc": "\u5982\u679C\u542F\u7528\uFF0C\u91CD\u590D\u7F16\u53F7\u5C06\u4F5C\u4E3A\u524D\u7F00\u6DFB\u52A0\u5728\u56FE\u7247\u540D\u79F0\u5F00\u5934\uFF0C\u5426\u5219\u5C06\u4F5C\u4E3A\u540E\u7F00\u6DFB\u52A0\u5728\u672B\u5C3E\u3002",
    "setting.dupNumberDelimiter.name": "\u91CD\u590D\u7F16\u53F7\u5206\u9694\u7B26",
    "setting.dupNumberDelimiter.desc": '\u7528\u4E8E\u751F\u6210\u91CD\u590D\u540D\u79F0\u7684\u7F16\u53F7\u524D\u7F00/\u540E\u7F00\u7684\u5206\u9694\u7B26\u3002\u4F8B\u5982\uFF0C\u5982\u679C\u503C\u4E3A "-"\uFF0C\u540E\u7F00\u5C06\u662F "-1"\u3001"-2"\u3001"-3"\uFF0C\u524D\u7F00\u5C06\u662F "1-"\u3001"2-"\u3001"3-"\u3002\u53EA\u5141\u8BB8\u4F7F\u7528\u6587\u4EF6\u540D\u4E2D\u6709\u6548\u7684\u5B57\u7B26\u3002',
    "setting.dupNumberAlways.name": "\u59CB\u7EC8\u6DFB\u52A0\u91CD\u590D\u7F16\u53F7",
    "setting.dupNumberAlways.desc": "\u5982\u679C\u542F\u7528\uFF0C\u5C06\u59CB\u7EC8\u4E3A\u56FE\u7247\u540D\u79F0\u6DFB\u52A0\u7F16\u53F7\u3002\u5426\u5219\uFF0C\u4EC5\u5728\u540D\u79F0\u91CD\u590D\u65F6\u6DFB\u52A0\u3002",
    "setting.autoRename.name": "\u81EA\u52A8\u91CD\u547D\u540D",
    "setting.autoRename.desc": "\u9ED8\u8BA4\u60C5\u51B5\u4E0B\uFF0C\u91CD\u547D\u540D\u524D\u603B\u662F\u663E\u793A\u786E\u8BA4\u5BF9\u8BDD\u6846\u3002\u5982\u679C\u542F\u7528\u6B64\u9009\u9879\uFF0C\u7C98\u8D34\u540E\u5C06\u81EA\u52A8\u91CD\u547D\u540D\u56FE\u7247\u3002",
    "setting.handleAllAttachments.name": "\u5904\u7406\u6240\u6709\u9644\u4EF6",
    "setting.handleAllAttachments.desc": `\u9ED8\u8BA4\u60C5\u51B5\u4E0B\uFF0C\u63D2\u4EF6\u4EC5\u5904\u7406\u540D\u79F0\u4EE5 "Pasted image " \u5F00\u5934\u7684\u56FE\u7247\uFF0C
\u8FD9\u662F Obsidian \u7528\u4E8E\u4ECE\u7C98\u8D34\u5185\u5BB9\u521B\u5EFA\u56FE\u7247\u7684\u524D\u7F00\u3002
\u5982\u679C\u542F\u7528\u6B64\u9009\u9879\uFF0C\u63D2\u4EF6\u5C06\u5904\u7406\u4FDD\u7BA1\u5E93\u4E2D\u521B\u5EFA\u7684\u6240\u6709\u9644\u4EF6\u3002`,
    "setting.excludeExtensionPattern.name": "\u6392\u9664\u6269\u5C55\u540D\u6A21\u5F0F",
    "setting.excludeExtensionPattern.desc": `\u4EC5\u5F53\u542F\u7528"\u5904\u7406\u6240\u6709\u9644\u4EF6"\u65F6\u6B64\u9009\u9879\u624D\u6709\u7528\u3002
\u7F16\u5199\u6B63\u5219\u8868\u8FBE\u5F0F\u6A21\u5F0F\u4EE5\u6392\u9664\u67D0\u4E9B\u6269\u5C55\u540D\u3002\u4EC5\u4F7F\u7528\u7B2C\u4E00\u884C\u3002`,
    "setting.disableRenameNotice.name": "\u7981\u7528\u91CD\u547D\u540D\u901A\u77E5",
    "setting.disableRenameNotice.desc": `\u5982\u679C\u4E0D\u60F3\u5728\u91CD\u547D\u540D\u56FE\u7247\u65F6\u770B\u5230\u901A\u77E5\uFF0C\u8BF7\u5173\u95ED\u6B64\u9009\u9879\u3002
\u6CE8\u610F\uFF0C\u5F53\u94FE\u63A5\u66F4\u6539\u65F6 Obsidian \u53EF\u80FD\u663E\u793A\u901A\u77E5\uFF0C\u6B64\u9009\u9879\u65E0\u6CD5\u7981\u7528\u8BE5\u901A\u77E5\u3002`
  },
  "zh-TW": {
    // Common
    "common.cancel": "\u53D6\u6D88",
    "common.yes": "\u78BA\u5B9A",
    "common.no": "\u53D6\u6D88",
    "common.to": "\u5230",
    // Errors & Notices
    "error.noActiveFile": "\u932F\u8AA4\uFF1A\u672A\u627E\u5230\u6D3B\u52D5\u6A94\u6848\u3002",
    "error.renameFailed": "\u91CD\u65B0\u547D\u540D\u5931\u6557",
    "error.noActiveEditor": "\u6C92\u6709\u6D3B\u52D5\u7684\u7DE8\u8F2F\u5668",
    "notice.renamed": "\u5DF2\u91CD\u65B0\u547D\u540D",
    "error.batchRenameFailed": "\u6279\u6B21\u91CD\u65B0\u547D\u540D\u5716\u7247\u5931\u6557\uFF1A\u751F\u6210\u7684\u540D\u7A31\u7121\u610F\u7FA9",
    // Image Rename Modal
    "modal.rename.title": "\u91CD\u65B0\u547D\u540D\u5716\u7247",
    "modal.rename.newName": "\u65B0\u540D\u7A31",
    "modal.rename.newNameDesc": "\u8ACB\u8F38\u5165\u5716\u7247\u7684\u65B0\u540D\u7A31\uFF08\u4E0D\u542B\u526F\u6A94\u540D\uFF09",
    "modal.rename.originPath": "\u539F\u8DEF\u5F91",
    "modal.rename.newPath": "\u65B0\u8DEF\u5F91",
    "modal.rename.button": "\u91CD\u65B0\u547D\u540D",
    "modal.rename.errorEmpty": "\u932F\u8AA4\uFF1A\u300C\u65B0\u540D\u7A31\u300D\u4E0D\u80FD\u70BA\u7A7A",
    // Batch Rename Modal
    "modal.batch.title": "\u6279\u6B21\u91CD\u65B0\u547D\u540D\u5D4C\u5165\u6A94\u6848",
    "modal.batch.namePattern": "\u540D\u7A31\u6A21\u5F0F",
    "modal.batch.namePatternDesc": "\u8ACB\u8F38\u5165\u5339\u914D\u6A94\u6848\u7684\u540D\u7A31\u6A21\u5F0F\uFF08\u6B63\u898F\u8868\u793A\u5F0F\uFF09",
    "modal.batch.extPattern": "\u526F\u6A94\u540D\u6A21\u5F0F",
    "modal.batch.extPatternDesc": "\u8ACB\u8F38\u5165\u5339\u914D\u6A94\u6848\u7684\u526F\u6A94\u540D\u6A21\u5F0F\uFF08\u6B63\u898F\u8868\u793A\u5F0F\uFF09",
    "modal.batch.nameReplace": "\u540D\u7A31\u66FF\u63DB",
    "modal.batch.nameReplaceDesc": "\u8ACB\u8F38\u5165\u7528\u65BC\u66FF\u63DB\u5339\u914D\u540D\u7A31\u7684\u5B57\u4E32\uFF08\u4F7F\u7528 $1\u3001$2 \u8868\u793A\u6B63\u898F\u5206\u7D44\uFF09",
    "modal.batch.tableOriginal": "\u539F\u8DEF\u5F91",
    "modal.batch.tableRenamed": "\u91CD\u65B0\u547D\u540D\u5F8C\u7684\u540D\u7A31",
    "modal.batch.renameAll": "\u5168\u90E8\u91CD\u65B0\u547D\u540D",
    "modal.batch.errorEmpty": "\u932F\u8AA4\uFF1A\u300C\u540D\u7A31\u6A21\u5F0F\u300D\u4E0D\u80FD\u70BA\u7A7A",
    "modal.batch.confirmTitle": "\u78BA\u8A8D\u5168\u90E8\u91CD\u65B0\u547D\u540D",
    "modal.batch.confirmMessage": "\u78BA\u5B9A\u8981\u7E7C\u7E8C\u55CE\uFF1F\u9019\u5C07\u91CD\u65B0\u547D\u540D\u6240\u6709\u7B26\u5408\u7684 {count} \u500B\u5716\u7247\u3002",
    // Commands
    "command.batchRename": "\u6279\u6B21\u91CD\u65B0\u547D\u540D\u5D4C\u5165\u6A94\u6848\uFF08\u76EE\u524D\u6A94\u6848\uFF09",
    "command.batchRenameAll": "\u7ACB\u5373\u6279\u6B21\u91CD\u65B0\u547D\u540D\u6240\u6709\u5716\u7247\uFF08\u76EE\u524D\u6A94\u6848\uFF09",
    // Settings
    "setting.imageNamePattern.name": "\u5716\u7247\u540D\u7A31\u6A21\u5F0F",
    "setting.imageNamePattern.desc": `\u6B64\u6A21\u5F0F\u6307\u5B9A\u5982\u4F55\u751F\u6210\u65B0\u540D\u7A31\u3002

\u53EF\u7528\u8B8A\u6578\uFF1A
- {{fileName}}\uFF1A\u6D3B\u52D5\u6A94\u6848\u7684\u540D\u7A31\uFF0C\u4E0D\u542B ".md" \u526F\u6A94\u540D\u3002
- {{dirName}}\uFF1A\u5305\u542B\u6587\u4EF6\u7684\u76EE\u9304\u540D\u7A31\uFF08\u6839\u76EE\u9304\u7D50\u679C\u70BA\u7A7A\u8B8A\u6578\uFF09\u3002
- {{imageNameKey}}\uFF1A\u6B64\u8B8A\u6578\u5F9E markdown \u6A94\u6848\u7684 frontmatter \u4E2D\u8B80\u53D6\uFF0C\u9375\u540D\u70BA "imageNameKey"\u3002
- {{DATE:$FORMAT}}\uFF1A\u4F7F\u7528 "$FORMAT" \u683C\u5F0F\u5316\u76EE\u524D\u65E5\u671F\uFF0C"$FORMAT" \u5FC5\u9808\u662F Moment.js \u683C\u5F0F\u5B57\u4E32\uFF0C\u4F8B\u5982 {{DATE:YYYY-MM-DD}}\u3002

\u7BC4\u4F8B\uFF08\u8B8A\u6578\uFF1AfileName = "\u6211\u7684\u7B46\u8A18", imageNameKey = "foo"\uFF09\uFF1A
- {{fileName}}\uFF1A\u6211\u7684\u7B46\u8A18, \u6211\u7684\u7B46\u8A18-1, \u6211\u7684\u7B46\u8A18-2
- {{imageNameKey}}\uFF1Afoo, foo-1, foo-2
- {{imageNameKey}}-{{DATE:YYYYMMDD}}\uFF1Afoo-20220408, foo-20220408-1, foo-20220408-2`,
    "setting.dupNumberAtStart.name": "\u91CD\u8907\u7DE8\u865F\u5728\u958B\u982D\uFF08\u6216\u672B\u5C3E\uFF09",
    "setting.dupNumberAtStart.desc": "\u5982\u679C\u555F\u7528\uFF0C\u91CD\u8907\u7DE8\u865F\u5C07\u4F5C\u70BA\u524D\u7DB4\u65B0\u589E\u5728\u5716\u7247\u540D\u7A31\u958B\u982D\uFF0C\u5426\u5247\u5C07\u4F5C\u70BA\u5F8C\u7DB4\u65B0\u589E\u5728\u672B\u5C3E\u3002",
    "setting.dupNumberDelimiter.name": "\u91CD\u8907\u7DE8\u865F\u5206\u9694\u7B26",
    "setting.dupNumberDelimiter.desc": '\u7528\u65BC\u751F\u6210\u91CD\u8907\u540D\u7A31\u7684\u7DE8\u865F\u524D\u7DB4/\u5F8C\u7DB4\u7684\u5206\u9694\u7B26\u3002\u4F8B\u5982\uFF0C\u5982\u679C\u503C\u70BA "-"\uFF0C\u5F8C\u7DB4\u5C07\u662F "-1"\u3001"-2"\u3001"-3"\uFF0C\u524D\u7DB4\u5C07\u662F "1-"\u3001"2-"\u3001"3-"\u3002\u53EA\u5141\u8A31\u4F7F\u7528\u6A94\u6848\u540D\u7A31\u4E2D\u6709\u6548\u7684\u5B57\u5143\u3002',
    "setting.dupNumberAlways.name": "\u59CB\u7D42\u65B0\u589E\u91CD\u8907\u7DE8\u865F",
    "setting.dupNumberAlways.desc": "\u5982\u679C\u555F\u7528\uFF0C\u5C07\u59CB\u7D42\u70BA\u5716\u7247\u540D\u7A31\u65B0\u589E\u7DE8\u865F\u3002\u5426\u5247\uFF0C\u50C5\u5728\u540D\u7A31\u91CD\u8907\u6642\u65B0\u589E\u3002",
    "setting.autoRename.name": "\u81EA\u52D5\u91CD\u65B0\u547D\u540D",
    "setting.autoRename.desc": "\u9810\u8A2D\u60C5\u6CC1\u4E0B\uFF0C\u91CD\u65B0\u547D\u540D\u524D\u7E3D\u662F\u986F\u793A\u78BA\u8A8D\u5C0D\u8A71\u6846\u3002\u5982\u679C\u555F\u7528\u6B64\u9078\u9805\uFF0C\u8CBC\u4E0A\u5F8C\u5C07\u81EA\u52D5\u91CD\u65B0\u547D\u540D\u5716\u7247\u3002",
    "setting.handleAllAttachments.name": "\u8655\u7406\u6240\u6709\u9644\u4EF6",
    "setting.handleAllAttachments.desc": `\u9810\u8A2D\u60C5\u6CC1\u4E0B\uFF0C\u5916\u639B\u50C5\u8655\u7406\u540D\u7A31\u4EE5 "Pasted image " \u958B\u982D\u7684\u5716\u7247\uFF0C
\u9019\u662F Obsidian \u7528\u65BC\u5F9E\u8CBC\u4E0A\u5167\u5BB9\u5EFA\u7ACB\u5716\u7247\u7684\u524D\u7DB4\u3002
\u5982\u679C\u555F\u7528\u6B64\u9078\u9805\uFF0C\u5916\u639B\u5C07\u8655\u7406\u4FDD\u7BA1\u5EAB\u4E2D\u5EFA\u7ACB\u7684\u6240\u6709\u9644\u4EF6\u3002`,
    "setting.excludeExtensionPattern.name": "\u6392\u9664\u526F\u6A94\u540D\u6A21\u5F0F",
    "setting.excludeExtensionPattern.desc": `\u50C5\u7576\u555F\u7528\u300C\u8655\u7406\u6240\u6709\u9644\u4EF6\u300D\u6642\u6B64\u9078\u9805\u624D\u6709\u7528\u3002
\u7DE8\u5BEB\u6B63\u898F\u8868\u793A\u5F0F\u6A21\u5F0F\u4EE5\u6392\u9664\u67D0\u4E9B\u526F\u6A94\u540D\u3002\u50C5\u4F7F\u7528\u7B2C\u4E00\u884C\u3002`,
    "setting.disableRenameNotice.name": "\u505C\u7528\u91CD\u65B0\u547D\u540D\u901A\u77E5",
    "setting.disableRenameNotice.desc": `\u5982\u679C\u4E0D\u60F3\u5728\u91CD\u65B0\u547D\u540D\u5716\u7247\u6642\u770B\u5230\u901A\u77E5\uFF0C\u8ACB\u95DC\u9589\u6B64\u9078\u9805\u3002
\u6CE8\u610F\uFF0C\u7576\u9023\u7D50\u66F4\u6539\u6642 Obsidian \u53EF\u80FD\u986F\u793A\u901A\u77E5\uFF0C\u6B64\u9078\u9805\u7121\u6CD5\u505C\u7528\u8A72\u901A\u77E5\u3002`
  }
};
var currentLang = "en";
function detectLanguage() {
  const locale = import_obsidian.moment.locale();
  if (locale.startsWith("zh-TW") || locale.startsWith("zh-HK")) {
    return "zh-TW";
  } else if (locale.startsWith("zh")) {
    return "zh";
  }
  return "en";
}
function initI18n() {
  currentLang = detectLanguage();
}
function t(key, replacements) {
  let text = translations[currentLang][key] || translations["en"][key] || key;
  if (replacements) {
    Object.keys(replacements).forEach((k) => {
      text = text.replace(new RegExp(`\\{${k}\\}`, "g"), String(replacements[k]));
    });
  }
  return text;
}

// src/batch.ts
var ImageBatchRenameModal = class extends import_obsidian2.Modal {
  constructor(app, activeFile, renameFunc, onClose) {
    super(app);
    this.activeFile = activeFile;
    this.renameFunc = renameFunc;
    this.onCloseExtra = onClose;
    this.state = {
      namePattern: "",
      extPattern: "",
      nameReplace: "",
      renameTasks: []
    };
  }
  onOpen() {
    this.containerEl.addClass("image-rename-modal");
    const { contentEl, titleEl } = this;
    titleEl.setText(t("modal.batch.title"));
    const namePatternSetting = new import_obsidian2.Setting(contentEl).setName(t("modal.batch.namePattern")).setDesc(t("modal.batch.namePatternDesc")).addText((text) => text.setValue(this.state.namePattern).onChange(
      (value) => __async(this, null, function* () {
        this.state.namePattern = value;
      })
    ));
    const npInputEl = namePatternSetting.controlEl.children[0];
    npInputEl.focus();
    const npInputState = lockInputMethodComposition(npInputEl);
    npInputEl.addEventListener("keydown", (e) => __async(this, null, function* () {
      if (e.key === "Enter" && !npInputState.lock) {
        e.preventDefault();
        if (!this.state.namePattern) {
          errorEl.innerText = t("modal.batch.errorEmpty");
          errorEl.style.display = "block";
          return;
        }
        this.matchImageNames(tbodyEl);
      }
    }));
    const extPatternSetting = new import_obsidian2.Setting(contentEl).setName(t("modal.batch.extPattern")).setDesc(t("modal.batch.extPatternDesc")).addText((text) => text.setValue(this.state.extPattern).onChange(
      (value) => __async(this, null, function* () {
        this.state.extPattern = value;
      })
    ));
    const extInputEl = extPatternSetting.controlEl.children[0];
    extInputEl.addEventListener("keydown", (e) => __async(this, null, function* () {
      if (e.key === "Enter") {
        e.preventDefault();
        this.matchImageNames(tbodyEl);
      }
    }));
    const nameReplaceSetting = new import_obsidian2.Setting(contentEl).setName(t("modal.batch.nameReplace")).setDesc(t("modal.batch.nameReplaceDesc")).addText((text) => text.setValue(this.state.nameReplace).onChange(
      (value) => __async(this, null, function* () {
        this.state.nameReplace = value;
      })
    ));
    const nrInputEl = nameReplaceSetting.controlEl.children[0];
    const nrInputState = lockInputMethodComposition(nrInputEl);
    nrInputEl.addEventListener("keydown", (e) => __async(this, null, function* () {
      if (e.key === "Enter" && !nrInputState.lock) {
        e.preventDefault();
        this.matchImageNames(tbodyEl);
      }
    }));
    const matchedContainer = contentEl.createDiv({
      cls: "matched-container"
    });
    const tableET = createElementTree(matchedContainer, {
      tag: "table",
      children: [
        {
          tag: "thead",
          children: [
            {
              tag: "tr",
              children: [
                {
                  tag: "td",
                  text: t("modal.batch.tableOriginal")
                },
                {
                  tag: "td",
                  text: t("modal.batch.tableRenamed")
                }
              ]
            }
          ]
        },
        {
          tag: "tbody"
        }
      ]
    });
    const tbodyEl = tableET.children[1].el;
    const errorEl = contentEl.createDiv({
      cls: "error",
      attr: {
        style: "display: none;"
      }
    });
    new import_obsidian2.Setting(contentEl).addButton((button) => {
      button.setButtonText(t("modal.batch.renameAll")).setClass("mod-cta").onClick(() => {
        new ConfirmModal(
          this.app,
          t("modal.batch.confirmTitle"),
          t("modal.batch.confirmMessage", { count: this.state.renameTasks.length }),
          () => {
            this.renameAll();
            this.close();
          }
        ).open();
      });
    }).addButton((button) => {
      button.setButtonText(t("common.cancel")).onClick(() => {
        this.close();
      });
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    this.onCloseExtra();
  }
  renameAll() {
    return __async(this, null, function* () {
      debugLog("renameAll", this.state);
      for (const task of this.state.renameTasks) {
        yield this.renameFunc(task.file, task.name);
      }
    });
  }
  matchImageNames(tbodyEl) {
    const { state } = this;
    const renameTasks = [];
    tbodyEl.empty();
    const fileCache = this.app.metadataCache.getFileCache(this.activeFile);
    if (!fileCache || !fileCache.embeds) return;
    const namePatternRegex = new RegExp(state.namePattern, "g");
    const extPatternRegex = new RegExp(state.extPattern);
    fileCache.embeds.forEach((embed) => {
      const file = this.app.metadataCache.getFirstLinkpathDest(embed.link, this.activeFile.path);
      if (!file) {
        console.warn("file not found", embed.link);
        return;
      }
      if (state.extPattern) {
        const m0 = extPatternRegex.exec(file.extension);
        if (!m0) return;
      }
      const stem = file.basename;
      namePatternRegex.lastIndex = 0;
      const m1 = namePatternRegex.exec(stem);
      if (!m1) return;
      let renamedName = file.name;
      if (state.nameReplace) {
        namePatternRegex.lastIndex = 0;
        renamedName = stem.replace(namePatternRegex, state.nameReplace);
        renamedName = `${renamedName}.${file.extension}`;
      }
      renameTasks.push({
        file,
        name: renamedName
      });
      createElementTree(tbodyEl, {
        tag: "tr",
        children: [
          {
            tag: "td",
            children: [
              {
                tag: "span",
                text: file.name
              },
              {
                tag: "div",
                text: file.path,
                attr: {
                  class: "file-path"
                }
              }
            ]
          },
          {
            tag: "td",
            children: [
              {
                tag: "span",
                text: renamedName
              },
              {
                tag: "div",
                text: path.join(file.parent.path, renamedName),
                attr: {
                  class: "file-path"
                }
              }
            ]
          }
        ]
      });
    });
    debugLog("new renameTasks", renameTasks);
    state.renameTasks = renameTasks;
  }
};
var ConfirmModal = class extends import_obsidian2.Modal {
  constructor(app, title, message, onConfirm) {
    super(app);
    this.title = title;
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText(this.title);
    contentEl.createEl("p", {
      text: this.message
    });
    new import_obsidian2.Setting(contentEl).addButton((button) => {
      button.setButtonText(t("common.yes")).setClass("mod-warning").onClick(() => {
        this.onConfirm();
        this.close();
      });
    }).addButton((button) => {
      button.setButtonText(t("common.no")).onClick(() => {
        this.close();
      });
    });
  }
};

// src/template.ts
var dateTmplRegex = /{{DATE:([^}]+)}}/gm;
var frontmatterTmplRegex = /{{frontmatter:([^}]+)}}/gm;
var replaceDateVar = (s, date) => {
  const m = dateTmplRegex.exec(s);
  if (!m) return s;
  return s.replace(m[0], date.format(m[1]));
};
var replaceFrontmatterVar = (s, frontmatter) => {
  if (!frontmatter) return s;
  const m = frontmatterTmplRegex.exec(s);
  if (!m) return s;
  return s.replace(m[0], frontmatter[m[1]] || "");
};
var renderTemplate = (tmpl, data, frontmatter) => {
  const now = window.moment();
  let text = tmpl;
  let newtext;
  while ((newtext = replaceDateVar(text, now)) != text) {
    text = newtext;
  }
  while ((newtext = replaceFrontmatterVar(text, frontmatter)) != text) {
    text = newtext;
  }
  text = text.replace(/{{imageNameKey}}/gm, data.imageNameKey).replace(/{{fileName}}/gm, data.fileName).replace(/{{dirName}}/gm, data.dirName).replace(/{{firstHeading}}/gm, data.firstHeading);
  return text;
};

// src/main.ts
var DEFAULT_SETTINGS = {
  imageNamePattern: "{{fileName}}",
  dupNumberAtStart: false,
  dupNumberDelimiter: "-",
  dupNumberAlways: false,
  autoRename: false,
  handleAllAttachments: false,
  excludeExtensionPattern: "",
  disableRenameNotice: false
};
var PASTED_IMAGE_PREFIX = "Pasted image ";
var PasteImageRenamePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.modals = [];
  }
  onload() {
    return __async(this, null, function* () {
      const pkg = require_package();
      console.log(`Plugin loading: ${pkg.name} ${pkg.version} BUILD_ENV=${"production"}`);
      initI18n();
      yield this.loadSettings();
      this.registerEvent(
        this.app.vault.on("create", (file) => {
          if (!(file instanceof import_obsidian3.TFile))
            return;
          const timeGapMs = (/* @__PURE__ */ new Date()).getTime() - file.stat.ctime;
          if (timeGapMs > 1e3)
            return;
          if (isMarkdownFile(file))
            return;
          if (isPastedImage(file)) {
            debugLog("pasted image created", file);
            this.startRenameProcess(file, this.settings.autoRename);
          } else {
            if (this.settings.handleAllAttachments) {
              debugLog("handleAllAttachments for file", file);
              if (this.testExcludeExtension(file)) {
                debugLog("excluded file by ext", file);
                return;
              }
              this.startRenameProcess(file, this.settings.autoRename);
            }
          }
        })
      );
      const startBatchRenameProcess = () => {
        this.openBatchRenameModal();
      };
      this.addCommand({
        id: "batch-rename-embeded-files",
        name: t("command.batchRename"),
        callback: startBatchRenameProcess
      });
      if (DEBUG) {
        this.addRibbonIcon("wand-glyph", "Batch rename embeded files", startBatchRenameProcess);
      }
      const batchRenameAllImages = () => {
        this.batchRenameAllImages();
      };
      this.addCommand({
        id: "batch-rename-all-images",
        name: t("command.batchRenameAll"),
        callback: batchRenameAllImages
      });
      if (DEBUG) {
        this.addRibbonIcon("wand-glyph", "Batch rename all images instantly (in the current file)", batchRenameAllImages);
      }
      this.addSettingTab(new SettingTab(this.app, this));
    });
  }
  startRenameProcess(file, autoRename = false) {
    return __async(this, null, function* () {
      const activeFile = this.getActiveFile();
      if (!activeFile) {
        new import_obsidian3.Notice(t("error.noActiveFile"));
        return;
      }
      const { stem, newName, isMeaningful } = this.generateNewName(file, activeFile);
      debugLog("generated newName:", newName, isMeaningful);
      if (!isMeaningful || !autoRename) {
        this.openRenameModal(file, isMeaningful ? stem : "", activeFile.path);
        return;
      }
      this.renameFile(file, newName, activeFile.path, true);
    });
  }
  renameFile(file, inputNewName, sourcePath, replaceCurrentLine) {
    return __async(this, null, function* () {
      const { name: newName } = yield this.deduplicateNewName(inputNewName, file);
      debugLog("deduplicated newName:", newName);
      const originName = file.name;
      const linkText = this.app.fileManager.generateMarkdownLink(file, sourcePath);
      const newPath = path.join(file.parent.path, newName);
      try {
        yield this.app.fileManager.renameFile(file, newPath);
      } catch (err) {
        new import_obsidian3.Notice(`${t("error.renameFailed")} ${newName}: ${err}`);
        throw err;
      }
      if (!replaceCurrentLine) {
        return;
      }
      const newLinkText = this.app.fileManager.generateMarkdownLink(file, sourcePath);
      debugLog("replace text", linkText, newLinkText);
      const editor = this.getActiveEditor();
      if (!editor) {
        new import_obsidian3.Notice(`${t("error.renameFailed")} ${newName}: ${t("error.noActiveEditor")}`);
        return;
      }
      const content = editor.getValue();
      const escapedLinkText = escapeRegExp(linkText);
      const linkRegex = new RegExp(escapedLinkText, "g");
      const matches = [];
      let match;
      while ((match = linkRegex.exec(content)) !== null) {
        matches.push({
          from: match.index,
          to: match.index + match[0].length
        });
      }
      if (matches.length > 0) {
        debugLog(`replacing ${matches.length} occurrence(s) in document`);
        const cursor = editor.getCursor();
        const changes = matches.reverse().map((pos) => ({
          from: editor.offsetToPos(pos.from),
          to: editor.offsetToPos(pos.to),
          text: newLinkText
        }));
        editor.transaction({ changes });
        editor.setCursor(cursor);
      } else {
        debugLog("no replacement needed, linkText not found in document");
      }
      if (!this.settings.disableRenameNotice) {
        new import_obsidian3.Notice(`${t("notice.renamed")} ${originName} ${t("common.to")} ${newName}`);
      }
    });
  }
  openRenameModal(file, newName, sourcePath) {
    const modal = new ImageRenameModal(
      this.app,
      file,
      newName,
      (confirmedName) => {
        debugLog("confirmedName:", confirmedName);
        this.renameFile(file, confirmedName, sourcePath, true);
      },
      () => {
        this.modals.splice(this.modals.indexOf(modal), 1);
      }
    );
    this.modals.push(modal);
    modal.open();
    debugLog("modals count", this.modals.length);
  }
  openBatchRenameModal() {
    const activeFile = this.getActiveFile();
    const modal = new ImageBatchRenameModal(
      this.app,
      activeFile,
      (file, name) => __async(this, null, function* () {
        yield this.renameFile(file, name, activeFile.path);
      }),
      () => {
        this.modals.splice(this.modals.indexOf(modal), 1);
      }
    );
    this.modals.push(modal);
    modal.open();
  }
  batchRenameAllImages() {
    return __async(this, null, function* () {
      const activeFile = this.getActiveFile();
      const fileCache = this.app.metadataCache.getFileCache(activeFile);
      if (!fileCache || !fileCache.embeds) return;
      const extPatternRegex = /jpe?g|png|gif|tiff|webp/i;
      for (const embed of fileCache.embeds) {
        const file = this.app.metadataCache.getFirstLinkpathDest(embed.link, activeFile.path);
        if (!file) {
          console.warn("file not found", embed.link);
          return;
        }
        const m0 = extPatternRegex.exec(file.extension);
        if (!m0) return;
        const { newName, isMeaningful } = this.generateNewName(file, activeFile);
        debugLog("generated newName:", newName, isMeaningful);
        if (!isMeaningful) {
          new import_obsidian3.Notice(t("error.batchRenameFailed"));
          break;
        }
        yield this.renameFile(file, newName, activeFile.path, false);
      }
    });
  }
  // returns a new name for the input file, with extension
  generateNewName(file, activeFile) {
    let imageNameKey = "";
    let firstHeading = "";
    let frontmatter;
    const fileCache = this.app.metadataCache.getFileCache(activeFile);
    if (fileCache) {
      debugLog("frontmatter", fileCache.frontmatter);
      frontmatter = fileCache.frontmatter;
      imageNameKey = (frontmatter == null ? void 0 : frontmatter.imageNameKey) || "";
      firstHeading = getFirstHeading(fileCache.headings);
    } else {
      console.warn("could not get file cache from active file", activeFile.name);
    }
    const stem = renderTemplate(
      this.settings.imageNamePattern,
      {
        imageNameKey,
        fileName: activeFile.basename,
        dirName: activeFile.parent.name,
        firstHeading
      },
      frontmatter
    );
    const meaninglessRegex = new RegExp(`[${this.settings.dupNumberDelimiter}\\s]`, "gm");
    return {
      stem,
      newName: stem + "." + file.extension,
      isMeaningful: stem.replace(meaninglessRegex, "") !== ""
    };
  }
  // newName: foo.ext
  deduplicateNewName(newName, file) {
    return __async(this, null, function* () {
      const dir = file.parent.path;
      const listed = yield this.app.vault.adapter.list(dir);
      debugLog("sibling files", listed);
      const newNameExt = path.extension(newName), newNameStem = newName.slice(0, newName.length - newNameExt.length - 1), newNameStemEscaped = escapeRegExp(newNameStem), delimiter = this.settings.dupNumberDelimiter, delimiterEscaped = escapeRegExp(delimiter);
      let dupNameRegex;
      if (this.settings.dupNumberAtStart) {
        dupNameRegex = new RegExp(
          `^(?<number>\\d+)${delimiterEscaped}(?<name>${newNameStemEscaped})\\.${newNameExt}$`
        );
      } else {
        dupNameRegex = new RegExp(
          `^(?<name>${newNameStemEscaped})${delimiterEscaped}(?<number>\\d+)\\.${newNameExt}$`
        );
      }
      debugLog("dupNameRegex", dupNameRegex);
      const dupNameNumbers = [];
      let isNewNameExist = false;
      for (let sibling of listed.files) {
        sibling = path.basename(sibling);
        if (sibling == newName) {
          isNewNameExist = true;
          continue;
        }
        const m = dupNameRegex.exec(sibling);
        if (!m) continue;
        dupNameNumbers.push(parseInt(m.groups.number));
      }
      if (isNewNameExist || this.settings.dupNumberAlways) {
        const newNumber = dupNameNumbers.length > 0 ? Math.max(...dupNameNumbers) + 1 : 1;
        if (this.settings.dupNumberAtStart) {
          newName = `${newNumber}${delimiter}${newNameStem}.${newNameExt}`;
        } else {
          newName = `${newNameStem}${delimiter}${newNumber}.${newNameExt}`;
        }
      }
      return {
        name: newName,
        stem: newName.slice(0, newName.length - newNameExt.length - 1),
        extension: newNameExt
      };
    });
  }
  getActiveFile() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    const file = view == null ? void 0 : view.file;
    debugLog("active file", file == null ? void 0 : file.path);
    return file;
  }
  getActiveEditor() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    return view == null ? void 0 : view.editor;
  }
  onunload() {
    this.modals.map((modal) => modal.close());
  }
  testExcludeExtension(file) {
    const pattern = this.settings.excludeExtensionPattern;
    if (!pattern) return false;
    return new RegExp(pattern).test(file.extension);
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
function getFirstHeading(headings) {
  if (headings && headings.length > 0) {
    for (const heading of headings) {
      if (heading.level === 1) {
        return heading.heading;
      }
    }
  }
  return "";
}
function isPastedImage(file) {
  if (file instanceof import_obsidian3.TFile) {
    if (file.name.startsWith(PASTED_IMAGE_PREFIX)) {
      return true;
    }
  }
  return false;
}
function isMarkdownFile(file) {
  if (file instanceof import_obsidian3.TFile) {
    if (file.extension === "md") {
      return true;
    }
  }
  return false;
}
var ImageRenameModal = class extends import_obsidian3.Modal {
  constructor(app, src, stem, renameFunc, onClose) {
    super(app);
    this.src = src;
    this.stem = stem;
    this.renameFunc = renameFunc;
    this.onCloseExtra = onClose;
  }
  onOpen() {
    this.containerEl.addClass("image-rename-modal");
    const { contentEl, titleEl } = this;
    titleEl.setText(t("modal.rename.title"));
    const imageContainer = contentEl.createDiv({
      cls: "image-container"
    });
    imageContainer.createEl("img", {
      attr: {
        src: this.app.vault.getResourcePath(this.src)
      }
    });
    let stem = this.stem;
    const ext = this.src.extension;
    const getNewName = (stem2) => stem2 + "." + ext;
    const getNewPath = (stem2) => path.join(this.src.parent.path, getNewName(stem2));
    const infoET = createElementTree(contentEl, {
      tag: "ul",
      cls: "info",
      children: [
        {
          tag: "li",
          children: [
            {
              tag: "span",
              text: t("modal.rename.originPath")
            },
            {
              tag: "span",
              text: this.src.path
            }
          ]
        },
        {
          tag: "li",
          children: [
            {
              tag: "span",
              text: t("modal.rename.newPath")
            },
            {
              tag: "span",
              text: getNewPath(stem)
            }
          ]
        }
      ]
    });
    const doRename = () => __async(this, null, function* () {
      debugLog("doRename", `stem=${stem}`);
      this.renameFunc(getNewName(stem));
    });
    const nameSetting = new import_obsidian3.Setting(contentEl).setName(t("modal.rename.newName")).setDesc(t("modal.rename.newNameDesc")).addText((text) => text.setValue(stem).onChange(
      (value) => __async(this, null, function* () {
        stem = sanitizer.filename(value);
        infoET.children[1].children[1].el.innerText = getNewPath(stem);
      })
    ));
    const nameInputEl = nameSetting.controlEl.children[0];
    nameInputEl.focus();
    const nameInputState = lockInputMethodComposition(nameInputEl);
    nameInputEl.addEventListener("keydown", (e) => __async(this, null, function* () {
      if (e.key === "Enter" && !nameInputState.lock) {
        e.preventDefault();
        if (!stem) {
          errorEl.innerText = t("modal.rename.errorEmpty");
          errorEl.style.display = "block";
          return;
        }
        doRename();
        this.close();
      }
    }));
    const errorEl = contentEl.createDiv({
      cls: "error",
      attr: {
        style: "display: none;"
      }
    });
    new import_obsidian3.Setting(contentEl).addButton((button) => {
      button.setButtonText(t("modal.rename.button")).onClick(() => {
        doRename();
        this.close();
      });
    }).addButton((button) => {
      button.setButtonText(t("common.cancel")).onClick(() => {
        this.close();
      });
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    this.onCloseExtra();
  }
};
var SettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName(t("setting.imageNamePattern.name")).setDesc(t("setting.imageNamePattern.desc")).setClass("long-description-setting-item").addText((text) => text.setPlaceholder("{{imageNameKey}}").setValue(this.plugin.settings.imageNamePattern).onChange(
      (value) => __async(this, null, function* () {
        this.plugin.settings.imageNamePattern = value;
        yield this.plugin.saveSettings();
      })
    ));
    new import_obsidian3.Setting(containerEl).setName(t("setting.dupNumberAtStart.name")).setDesc(t("setting.dupNumberAtStart.desc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.dupNumberAtStart).onChange(
      (value) => __async(this, null, function* () {
        this.plugin.settings.dupNumberAtStart = value;
        yield this.plugin.saveSettings();
      })
    ));
    new import_obsidian3.Setting(containerEl).setName(t("setting.dupNumberDelimiter.name")).setDesc(t("setting.dupNumberDelimiter.desc")).addText((text) => text.setValue(this.plugin.settings.dupNumberDelimiter).onChange(
      (value) => __async(this, null, function* () {
        this.plugin.settings.dupNumberDelimiter = sanitizer.delimiter(value);
        yield this.plugin.saveSettings();
      })
    ));
    new import_obsidian3.Setting(containerEl).setName(t("setting.dupNumberAlways.name")).setDesc(t("setting.dupNumberAlways.desc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.dupNumberAlways).onChange(
      (value) => __async(this, null, function* () {
        this.plugin.settings.dupNumberAlways = value;
        yield this.plugin.saveSettings();
      })
    ));
    new import_obsidian3.Setting(containerEl).setName(t("setting.autoRename.name")).setDesc(t("setting.autoRename.desc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.autoRename).onChange(
      (value) => __async(this, null, function* () {
        this.plugin.settings.autoRename = value;
        yield this.plugin.saveSettings();
      })
    ));
    new import_obsidian3.Setting(containerEl).setName(t("setting.handleAllAttachments.name")).setDesc(t("setting.handleAllAttachments.desc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.handleAllAttachments).onChange(
      (value) => __async(this, null, function* () {
        this.plugin.settings.handleAllAttachments = value;
        yield this.plugin.saveSettings();
      })
    ));
    new import_obsidian3.Setting(containerEl).setName(t("setting.excludeExtensionPattern.name")).setDesc(t("setting.excludeExtensionPattern.desc")).setClass("single-line-textarea").addTextArea((text) => text.setPlaceholder("docx?|xlsx?|pptx?|zip|rar").setValue(this.plugin.settings.excludeExtensionPattern).onChange(
      (value) => __async(this, null, function* () {
        this.plugin.settings.excludeExtensionPattern = value;
        yield this.plugin.saveSettings();
      })
    ));
    new import_obsidian3.Setting(containerEl).setName(t("setting.disableRenameNotice.name")).setDesc(t("setting.disableRenameNotice.desc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.disableRenameNotice).onChange(
      (value) => __async(this, null, function* () {
        this.plugin.settings.disableRenameNotice = value;
        yield this.plugin.saveSettings();
      })
    ));
  }
};
